#!/bin/bash 

#
# hdmi/analog output toggle
#

pactl info | grep -i "default source.*hdmi" > /dev/null  

if [[ `echo $?` -eq 1 ]]; then
    pactl set-card-profile 0 output:hdmi-surround
else
    pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
fi
