#!/bin/bash
# access translate.google.com from terminal

if [[ $1 = -h || $1 = --help ]]
then
    echo "$help"
    exit
fi

    source="cs"
    targets=(en)

    for i in ${targets[@]}
    do

        result=$(curl -s -i --user-agent "" -d "sl=$source" -d "tl=${i}" --data-urlencode "text=$1" https://translate.google.com)
        encoding=$(awk '/Content-Type: .* charset=/ {sub(/^.*charset=["'\'']?/,""); sub(/[ "'\''].*$/,""); print}' <<<"$result")
        #iconv -f $encoding <<<"$result" | awk 'BEGIN {RS="<div"};/<span[^>]* id=["'\'']?result_box["'\'']?/ {sub(/^.*id=["'\'']?result_box["'\'']?(>| [^>]*>)([ \n\t]*<[^>]*>)*/,"");sub(/<.*$/,"");print}' | html2text -utf8
        iconv -f $encoding <<<"$result" |  awk 'BEGIN {RS="</div>"};/<span[^>]* id=["'\'']?result_box["'\'']?/' | html2text -utf8
    done
exit

