#!/bin/bash

    if [ -f "${1}" ] ; then
        case "${1}" in
            *.tar.bz2)  tar xjvf   "${1}" ;;
            *.tar.gz)   tar xzvf   "${1}" ;;
            *.tbz2)     tar xjvf   "${1}" ;;
            *.bz2)      bunzip2    "${1}" ;;
            *.rar)      unrar x    "${1}" ;;
            *.tar)      tar xfv    "${1}" ;;
            *.tgz)      tar xzfv   "${1}" ;;
            *.zip)      unzip      "${1}" ;;
            *.gz)       gunzip     "${1}" ;;
            *.Z)        uncompress "${1}" ;;
            *)          echo "'${1}' cannot be extracted via extract()" ;;
        esac
    else
        echo "'${1}' is not a valid file"
    fi

