#!/bin/bash 
 
# Add to .zshrc alias ff="source newf"
#
# Usage:
#
# $> ff search_string
#
# Will result in numbered find output
# Pressing 0, 1, 2 keys will lead you to specific destination
# Requires zsh and zsh alias -s for filetypes (alias -s php=vim) to open php file in vim
#
# Creates aliases on the fly
 
 
COLOR_PURPLE='\033[0;34m'
COLOR_NC='\033[0m' # No Color
COLOR_WHITE='\033[1;37m'
COLOR_LIGHT_GREEN='\033[1;32m'
COLOR_LIGHT_GRAY='\033[0;37m'
COLOR_DEP=''
 
j=0
if [[ -f ~/.tmp/fListAliases ]]; then
ALIAS_COUNT=`cat ~/.tmp/fListAliases | wc -l`
else
ALIAS_COUNT=0
fi
 
mkdir -p ~/.tmp
rm -f ~/.tmp/fListAliases
rm -f ~/.tmp/lastFind1
rm -f ~/.tmp/fListResults
 
for (( k=0; k < ${ALIAS_COUNT}; k++ )); do
unalias ${k} 2>/dev/null
done
 
touch ~/.tmp/fListResults 
s
ls -lrt >> ~/.tmp/fListResults 
sed -i '1d' ~/.tmp/fListResults 


while read -r line;do

    echo ${line} | grep "^d" >> /dev/null
    if [[ $? -eq 0 ]]; then
        COLOR_DEP=${COLOR_PURPLE} 
    else    
        COLOR_DEP=${COLOR_NC}
    fi
#echo $line
    fileName="$(echo ${line} | tr -s " " " " | cut -d " " -f9-)"
    fileNameEdited="$(echo ${line}  | tr -s " " " " |  cut -d " " -f9- | sed -e 's/[]\/() $.*^|[]/\\&/g' | sed -e 's/"/\\/g' | sed -e "s/'/\'/g")" 
#echo $fileName
    echo "${COLOR_LIGHT_GREEN} ${j} ${COLOR_NC} : ${COLOR_DEP}${fileName}${COLOR_NC}" 

    echo "${j} ':' ${PWD}/${fileName}" >> ~/.tmp/lastFind1
    echo "alias -g ${j}=\"${PWD}/${fileNameEdited}\" " >> ~/.tmp/fListAliases

    j=$((j+1))
done < ~/.tmp/fListResults
echo "${COLOR_LIGHT_GREEN}__________________________________${COLOR_NC}"
 
 
if [[ ! -f ~/.tmp/fListAliases ]]; then
echo "No matches found"
else
. ~/.tmp/fListAliases
fi
