#!/bin/bash
TXB=0
for txbytes in /sys/class/net/*/statistics/tx_bytes ; do
  let TXB+=$(<$txbytes)
done

sleep 2

TXBN=0
for txbytes in /sys/class/net/*/statistics/tx_bytes ; do
  let TXBN+=$(<$txbytes)
done
#divide by two for the period, multiply by 10 to allow a correct decimal place
TXDIF=$(echo $(((TXBN - TXB) * 5  )))

SPEEDU="B/s"
ARROW="↑ "

if [ $TXDIF -ge 10240 ]; then
	SPEEDU="Kb/s"
	TXDIF=$(echo $((TXDIF / 1024 )) )
fi

if [ $TXDIF -ge 10240 ]; then
	SPEEDU="Mb/s"
	TXDIF=$(echo $((TXDIF / 1024 )) )
fi

if [ $TXDIF -ge 10240 ]; then
	SPEEDU="Gb/s"
	TXDIF=$(echo $((TXDIF / 1024 )) )
fi

TXDIFF=$(($TXDIF % 10 ))
TXDIFI=$(( $TXDIF / 10 ))
TXDIF="$TXDIFI"

if [ $TXDIFF -ne 0 ]; then
	TXDIF=$( echo  "$TXDIFI.$TXDIFF" )
fi

echo "$ARROW $TXDIF$SPEEDU"
